name: 'build'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "trevone"
          password: ${{ secrets.DOCKER_AUTH_GITHUB }}
          repository: zimbo-link/terminal-base
          tags: latest
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "trevone"
          password: ${{ secrets.DOCKER_AUTH_GITHUB }}
          repository: zimbo-link/terminal-base/terminal-distro
          tags: latest